apiVersion: v1
kind: Secret
metadata:
  name: tunnel-credentials
type: Opaque
data:
  credentials.json: eyJBY2NvdW50VGFnIjoiYzQ0YTFkNTJhNTdkYTgzODQ1ODgzMDljNjlkY2M4YTYiLCJUdW5uZWxTZWNyZXQiOiJqdHh5ZjMzKzNuTGVicTZzQWErRjErcEVSQ3MzLzVXVEk1c2F2T1ZhWkc0PSIsIlR1bm5lbElEIjoiOGJmMzIyNTUtZjkzNi00MWYxLWEzMTgtYWZlNGZjZTFhOGZlIiwiRW5kcG9pbnQiOiIifQ==
